const defaultProducts=[
 {id:'chocolate-granola',name:'Chocolate Granola',category:'granola',price:320,color:'brown',tag:'Bestseller',desc:'Crunchy rolled oats, nuts and rich cocoa baked into a deliciously wholesome breakfast and snack.',ingredients:['Rolled oats','Honey','Almonds','Kodo millet','Cocoa'],image:null},
 {id:'berries-granola',name:'Berries Granola',category:'granola',price:320,color:'orange',tag:'Fruity crunch',desc:'Crispy granola infused with the goodness of berries for a fruity, wholesome crunch.',ingredients:['Rolled oats','Jowar flakes','Almonds','Dried strawberry','Dried cranberry'],image:null},
 {id:'apple-cinnamon',name:'Apple Cinnamon Granola',category:'granola',price:320,color:'yellow',tag:'New',desc:'A comforting blend of apples, cinnamon and crunchy oats that brings warmth to every bite.',ingredients:['Rolled oats','Honey','Grated apple','Almonds','Cinnamon'],image:null},
 {id:'cashew-truffles',name:'Cashew Truffles',category:'bites',price:349,color:'sage',tag:'Rich & creamy',desc:'Rich, creamy truffles made with premium cashews and naturally sweetened with honey.',ingredients:['Oats','Cashew','Almond','Honey','Chia seeds'],image:null},
 {id:'dates-nuts',name:'Dates & Nuts Bites',category:'bites',price:319,color:'brown',tag:'Energy bite',desc:'A nourishing blend of dates, nuts and seeds that delivers natural sweetness and lasting energy.',ingredients:['Dates','Cashew','Sunflower seeds','Flax seeds','Pumpkin seeds'],image:'assets/date-walnut-cake.webp'},
 {id:'cocoa-ragi',name:'Cocoa Ragi Bites',category:'bites',price:249,color:'brown',tag:'Everyday favourite',desc:'A wholesome blend of ragi and cocoa, naturally crafted for a satisfying everyday snack.',ingredients:['Ragi flour','Cashew','Almond','Jaggery','Cocoa'],image:null},
 {id:'crunchy-munchy',name:'Crunchy Munchy Snack',category:'bars',price:259,color:'orange',tag:'Crowd favourite',desc:'A crunchy medley of oats, millets, nuts and tangy spices that makes healthy snacking irresistible.',ingredients:['Rolled oats','Peanuts','Bajra flakes','Cashews','Tamarind'],image:'assets/crunchy-munchy.webp'},
 {id:'ragi-brownie',name:'Ragi Brownie',category:'bars',price:299,color:'brown',tag:'Soft & fudgy',desc:'Soft, fudgy brownies made with wholesome ingredients for a richer, more mindful indulgence.',ingredients:['Ragi flour','Wheat flour','Jaggery','Cocoa powder','Chocolate'],image:'assets/ragi-brownie.webp'}
];
const products=JSON.parse(localStorage.getItem('nutty-products-admin')||'null')||defaultProducts;
let cart=JSON.parse(localStorage.getItem('nutty-cart')||'[]');let currentProduct=null;
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function imageMarkup(p,small=false){return p.image?`<div class="product-image photo ${p.color}"><img src="${p.image}" alt="${p.name}"></div>`:`<div class="product-image ${p.color}"><div class="shape"></div></div>`}
function renderProducts(filter='all'){const list=filter==='all'?products:products.filter(p=>p.category===filter);$('#product-count').textContent=`${list.length} snacks`;$('#product-grid').innerHTML=list.map(p=>`<article class="product-card" data-id="${p.id}">${imageMarkup(p)}<div class="product-info"><div><h3>${p.name}</h3><p>200 g · ${p.category}</p></div><span class="product-price">₹${p.price}</span></div></article>`).join('');$$('.product-card').forEach(c=>c.addEventListener('click',()=>openModal(products.find(p=>p.id===c.dataset.id))))}
function openModal(p){currentProduct=p;$('#modal-category').textContent=p.tag;$('#modal-title').textContent=p.name;$('#modal-description').textContent=p.desc;$('#modal-visual').innerHTML=imageMarkup(p);$('#modal-ingredients').innerHTML=p.ingredients.map(i=>`<span class="ingredient">${i}</span>`).join('');$('#modal-price').textContent=`₹${p.price}`;$('#modal-backdrop').classList.add('open')}
function addToCart(p){const item=cart.find(i=>i.id===p.id);item?item.qty++:cart.push({id:p.id,qty:1});saveCart();showToast(`${p.name} added to your bag`);renderCart()}
function saveCart(){localStorage.setItem('nutty-cart',JSON.stringify(cart));$('#cart-count').textContent=cart.reduce((s,i)=>s+i.qty,0)}
function renderCart(){const area=$('#cart-items');if(!cart.length){area.innerHTML='<p class="cart-empty">Your bag is waiting for something delicious.<br><br>Explore the pantry and add your favourites here.</p>';$('#cart-total').textContent='₹0';return}let total=0;area.innerHTML=cart.map(item=>{const p=products.find(x=>x.id===item.id);total+=p.price*item.qty;return `<div class="cart-line"><div class="cart-thumb ${p.color}"><div class="shape"></div></div><div class="cart-line-info"><strong>${p.name}</strong><small>200 g pack · ₹${p.price}</small><div class="cart-line-actions"><button class="qty-btn" data-action="minus" data-id="${p.id}">−</button><span>${item.qty}</span><button class="qty-btn" data-action="plus" data-id="${p.id}">+</button><button class="remove" data-action="remove" data-id="${p.id}">Remove</button></div></div><span class="cart-line-price">₹${p.price*item.qty}</span></div>`}).join('');$('#cart-total').textContent=`₹${total}`;$$('.qty-btn,.remove').forEach(b=>b.addEventListener('click',()=>{const item=cart.find(i=>i.id===b.dataset.id);if(b.dataset.action==='plus')item.qty++;if(b.dataset.action==='minus')item.qty--;if(b.dataset.action==='remove'||item.qty<=0)cart=cart.filter(i=>i.id!==b.dataset.id);saveCart();renderCart()}))}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts(b.dataset.filter)}));$('#modal-close').addEventListener('click',()=>$('#modal-backdrop').classList.remove('open'));$('#modal-backdrop').addEventListener('click',e=>{if(e.target.id==='modal-backdrop')e.currentTarget.classList.remove('open')});$('#modal-add').addEventListener('click',()=>{addToCart(currentProduct);$('#modal-backdrop').classList.remove('open');$('#cart-drawer').classList.add('open')});$('#cart-open').addEventListener('click',()=>{renderCart();$('#cart-drawer').classList.add('open')});$('#cart-close').addEventListener('click',()=>$('#cart-drawer').classList.remove('open'));$('#checkout').addEventListener('click',()=>{if(!cart.length){showToast('Add something delicious first');return}const lines=cart.map(i=>{const p=products.find(x=>x.id===i.id);return `${p.name} x${i.qty}`}).join(', ');window.open(`https://wa.me/918108398025?text=${encodeURIComponent(`Hi NuttyWonders! I'd like to order: ${lines}. Please share the total and payment details.`)}`,'_blank')});$('#newsletter-form').addEventListener('submit',e=>{e.preventDefault();$('#newsletter-note').textContent='You’re on the list. Welcome to the good stuff!';e.target.reset()});$('#menu-toggle').addEventListener('click',()=>{const nav=$('.desktop-nav');nav.style.display=nav.style.display==='flex'?'none':'flex';nav.style.position='absolute';nav.style.top='78px';nav.style.left='0';nav.style.right='0';nav.style.padding='20px 5vw';nav.style.background='var(--cream)';nav.style.flexDirection='column'});renderProducts();saveCart();if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js'));
