server {
  listen 3000;
  listen [::]:3000;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(css|js|png|jpe?g|webp|svg|ico)$ {
    expires 7d;
    add_header Cache-Control "public, immutable";
  }
}
